const fs = require('fs');
const assert = require('assert');
const css = fs.readFileSync('assets/css/styles.css','utf8');
const js = fs.readFileSync('assets/js/focus-reading.js','utf8');
assert(css.includes('v3.53.3 — hard mobile viewport containment'));
assert(css.includes('#workflow .focus-reading-toolbar'));
assert(css.includes('overflow-x:hidden'));
assert(!js.includes("{ id:'workflow', label:'Review & Trust' }"));
assert(!js.includes('syncWorkflowFocusForViewport'));
console.log('PASS mobile v3.53.3 viewport containment');
